// <auto-generated />
namespace Lilybot.Shopping.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSlackUserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSlackUserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201610020951413_Add-SlackUserId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
